### ISSUE TITLE
all "distinctiveness" scores seem to be 0

### ISSUE THREAD

**Issue by macfarlandian** [Wordseer/wordseer#230]
is this a preprocessor issue?

**Comment by MartiHearst** [comment]
Maybe this is a from __future__ import division issue?

**Comment by macfarlandian** [comment]
the JS app is requesting frequent words for the overlay menu from words_view.py ... it should be requesting them from associated_words_view.py. 

THEN, associated_words_view.py should compute a tf*idf score for matching sentences within the slice (containing the co-occurring word) instead of just term frequency (as it currently does)

**Comment by macfarlandian** [comment]
pretty sure I reopened this because of the issues (mostly) fixed in db0ca46b5b11431d0637371ad1c943d8b05172f8, b89e2b3b1f4b603535acabebaf8c5ffc6ac177ab, f64309165660debebc5c08061df02744fe946b2a, so closing again

**Comment by macfarlandian** [comment]
see #244 for a lingering issue related to this
