### ISSUE TITLE
uploading too many files puts system into broken state

### ISSUE THREAD

**Issue by MartiHearst** [Wordseer/wordseer#279]
I tried uploading all of the files from the "personals" collection.  This gave me an error which I believe originated from OS X (see attached screenshot).  After that, I could no longer get the uploader tool out if its bad state (see screenshot).
![screen shot 2015-07-03 at 7 32 13 pm](https://cloud.githubusercontent.com/assets/114297/8506142/5d94b004-21ba-11e5-9acc-196fcf76dc1c.png)

![screen shot 2015-07-03 at 7 30 14 pm](https://cloud.githubusercontent.com/assets/114297/8506130/f4436d02-21b9-11e5-8120-f7b98591061c.png)

**Comment by macfarlandian** [comment]
@MartiHearst pretty sure i know how to prevent this from happening but it's going to be a pain to implement, so for now just know that you can recover from this error state by killing the server with a keyboard interrupt and restarting it. i'll get to this eventually.
