### ISSUE TITLE
It can't finish processing.

### ISSUE THREAD

**Issue by medeor** [Wordseer/wordseer#330]
I'm trying the shortest dataset which is post1.xml but it still couldn't complete the processing part. I am constantly getting this message on terminal at every 2 seconds.

werkzeug:INFO:  127.0.0.1 - - [29/Sep/2016 06:26:43] "GET /logs/3?start=0 HTTP/1.1" 200 -

I tried to load it again but it's the same. I am using a Macbook Pro 2012 Mid.

**Comment by macfarlandian** [comment]
that message is nothing to worry about, it's just the log page polling for updates. Is it printing any other messages that might be errors?

**Comment by medeor** [comment]
It was because my Java was not updated. However, it should have warned me about that I think. In another computer that doesn't have Java installed it warned me about it.
